include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  errors:
    invalid_annotation_target: ignore

  # Freezed
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - packages/video_player

  plugins:
    - custom_lint

custom_lint:
  rules:
    - missing_provider_scope: false
