name: unofficial_chzzk_android_tv
description: "UnOfficial Chzzk for Android TV"
publish_to: "none"

version: 0.3.3+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # riverpod
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  # freezed
  freezed_annotation: ^2.4.4
  # CRUD
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  logger: ^2.4.0

  wakelock_plus: ^1.2.7
  flutter_hls_parser: ^2.0.1
  # webview for login
  flutter_inappwebview: ^6.0.0
  # image
  gif: ^2.3.0
  # cached_network_image: ^3.4.0
  # router
  go_router: ^14.2.1
  # websocket
  web_socket_channel: ^3.0.1
  # utils
  intl: ^0.19.0
  hangul: ^0.6.0
  html: ^0.15.4
  # local database
  shared_preferences: ^2.2.2
  flutter_markdown:
    ^0.7.3+1
    # video
  # video_player: ^2.9.1

  # Custom video player for adding query parameters to sub m3u8 address
  video_player:
    path: ./packages/video_player/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # riverpod
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  # freezed
  freezed: ^2.5.2
  # retrofit
  retrofit_generator: ^8.1.2
  # common
  json_serializable: ^6.8.0
  build_runner: ^2.4.8
  # database

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
