name: unofficial_chzzk_android_tv
description: "A Chzzk TV for Android TV"
publish_to: "none"
version: 0.2.2

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  wakelock_plus: ^1.1.4
  dio: ^5.4.0
  flutter_inappwebview: ^6.0.0
  intl: ^0.19.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_hls_parser: ^2.0.1
  video_player: ^2.8.3
  chewie: ^1.7.5
  hangul: ^0.6.0
  gif: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  custom_lint: ^0.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
