import 'package:flutter/material.dart';

import '../../../domain/entities/settings_preferences.dart';
import '../../settings_screen_string.dart';
import '../settings_preference_models.dart';

part 'chat_settings_quick_position.dart';

final chatSettingsPreferences = <SettingsPreferenceItem>[
  chatPreference(
    title: SettingsScreenString.chatOverlayQuickPositionTitle,
    description: SettingsScreenString.chatOverlayQuickPositionDescription,
    optionSet: settingsOverlayChatQuickPositionOptionSet,
    read: (settings) => settings.overlayChatQuickPositionIndex,
    write: _withOverlayChatQuickPositionIndex,
    label: SettingsScreenString.overlayChatQuickPositionLabel,
    actionIcon: Icons.open_with,
    icon: _overlayChatQuickPositionIcon,
    iconAlignment: _overlayChatQuickPositionIconAlignment,
    wrapSlider: true,
  ),
  chatPreference(
    title: SettingsScreenString.chatOverlayPositionXTitle,
    description: SettingsScreenString.chatOverlayPositionXDescription,
    optionSet: settingsPositionOptionSet,
    read: (settings) => settings.overlayChatPositionX,
    write: (settings, value) => _withOverlayChatPosition(settings, x: value),
    label: SettingsScreenString.percent,
    actionIcon: Icons.open_with,
  ),
  chatPreference(
    title: SettingsScreenString.chatOverlayPositionYTitle,
    description: SettingsScreenString.chatOverlayPositionYDescription,
    optionSet: settingsPositionOptionSet,
    read: (settings) => settings.overlayChatPositionY,
    write: (settings, value) => _withOverlayChatPosition(settings, y: value),
    label: SettingsScreenString.percent,
    actionIcon: Icons.open_with,
  ),
  chatPreference(
    title: SettingsScreenString.chatOverlayPanelHeightTitle,
    description: SettingsScreenString.chatOverlayPanelHeightDescription,
    optionSet: settingsOverlayChatPanelHeightOptionSet,
    read: (settings) => settings.overlayChatPanelHeight,
    write: (settings, value) => settings.copyWith(
      overlayChatPanelHeight: value,
    ),
    label: SettingsScreenString.percent,
    actionIcon: Icons.height,
  ),
  chatPreference(
    title: SettingsScreenString.chatOverlayPanelWidthTitle,
    description: SettingsScreenString.chatOverlayPanelWidthDescription,
    optionSet: settingsOverlayChatPanelWidthOptionSet,
    read: (settings) => settings.overlayChatPanelWidth,
    write: (settings, value) => settings.copyWith(
      overlayChatPanelWidth: value,
    ),
    label: SettingsScreenString.percent,
    actionIcon: Icons.swap_horiz,
  ),
  chatPreference(
    title: SettingsScreenString.chatSidePositionTitle,
    description: SettingsScreenString.chatSidePositionDescription,
    optionSet: settingsSideChatPositionOptionSet,
    read: (settings) => settings.sideChatPositionIndex,
    write: (settings, value) => settings.copyWith(
      sideChatPositionIndex: value,
      chatSidePanelPositionX: value == 0 ? 0 : 100,
    ),
    label: SettingsScreenString.sideChatPositionLabel,
    actionIcon: Icons.compare_arrows,
    icon: _sideChatPositionIcon,
    iconAlignment: _sideChatPositionIconAlignment,
  ),
  chatPreference(
    title: SettingsScreenString.chatSideWidthTitle,
    description: SettingsScreenString.chatSideWidthDescription,
    optionSet: settingsChatSidePanelWidthOptionSet,
    read: (settings) => settings.chatSidePanelWidth,
    write: (settings, value) => settings.copyWith(chatSidePanelWidth: value),
    label: SettingsScreenString.percent,
    actionIcon: Icons.view_sidebar_outlined,
  ),
  chatPreference(
    title: SettingsScreenString.chatMessageFontSizeTitle,
    description: SettingsScreenString.chatMessageFontSizeDescription,
    optionSet: settingsChatMessageFontSizeOptionSet,
    read: (settings) => settings.chatMessageFontSize,
    write: (settings, value) => settings.copyWith(chatMessageFontSize: value),
    label: SettingsScreenString.rawValue,
    actionIcon: Icons.format_size,
  ),
  chatPreference(
    title: SettingsScreenString.chatPanelTransparencyTitle,
    description: SettingsScreenString.chatPanelTransparencyDescription,
    optionSet: settingsTransparencyOptionSet,
    read: (settings) => settings.chatPanelTransparency,
    write: (settings, value) => settings.copyWith(
      chatPanelTransparency: value,
    ),
    label: SettingsScreenString.percent,
    actionIcon: Icons.opacity,
  ),
  chatPreference(
    title: SettingsScreenString.chatContainerTitle,
    description: SettingsScreenString.chatContainerDescription,
    optionSet: settingsToggleOptionSet,
    read: (settings) => settings.useChatPanelContainer,
    write: (settings, value) => settings.copyWith(
      useChatPanelContainer: value,
    ),
    label: SettingsScreenString.toggleLabel,
    actionIcon: Icons.rounded_corner,
  ),
  chatPreference(
    title: SettingsScreenString.chatBubbleTransparencyTitle,
    description: SettingsScreenString.chatBubbleTransparencyDescription,
    optionSet: settingsTransparencyOptionSet,
    read: (settings) => settings.chatBubbleTransparency,
    write: (settings, value) => settings.copyWith(
      chatBubbleTransparency: value,
    ),
    label: SettingsScreenString.percent,
    actionIcon: Icons.opacity,
  ),
  chatPreference(
    title: SettingsScreenString.chatHorizontalMarginTitle,
    description: SettingsScreenString.chatHorizontalMarginDescription,
    optionSet: settingsMarginOptionSet,
    read: (settings) => settings.chatContainerHorizontalMargin,
    write: (settings, value) => settings.copyWith(
      chatContainerHorizontalMargin: value,
    ),
    label: SettingsScreenString.rawValue,
    actionIcon: Icons.align_horizontal_center,
  ),
  chatPreference(
    title: SettingsScreenString.chatVerticalMarginTitle,
    description: SettingsScreenString.chatVerticalMarginDescription,
    optionSet: settingsMarginOptionSet,
    read: (settings) => settings.chatContainerVerticalMargin,
    write: (settings, value) => settings.copyWith(
      chatContainerVerticalMargin: value,
    ),
    label: SettingsScreenString.rawValue,
    actionIcon: Icons.align_vertical_center,
  ),
  chatPreference(
    title: SettingsScreenString.chatBubbleVerticalGapTitle,
    description: SettingsScreenString.chatBubbleVerticalGapDescription,
    optionSet: settingsMarginOptionSet,
    read: (settings) => settings.chatBubbleVerticalGap,
    write: (settings, value) => settings.copyWith(
      chatBubbleVerticalGap: value,
    ),
    label: SettingsScreenString.rawValue,
    actionIcon: Icons.format_line_spacing,
  ),
  chatPreference(
    title: SettingsScreenString.chatTimeTitle,
    description: SettingsScreenString.chatTimeDescription,
    optionSet: settingsToggleOptionSet,
    read: (settings) => settings.showChatTime,
    write: (settings, value) => settings.copyWith(showChatTime: value),
    label: SettingsScreenString.toggleLabel,
    actionIcon: Icons.schedule,
  ),
  chatPreference(
    title: SettingsScreenString.chatNicknameTitle,
    description: SettingsScreenString.chatNicknameDescription,
    optionSet: settingsToggleOptionSet,
    read: (settings) => settings.showNickname,
    write: (settings, value) => settings.copyWith(showNickname: value),
    label: SettingsScreenString.toggleLabel,
    actionIcon: Icons.badge_outlined,
  ),
  chatPreference(
    title: SettingsScreenString.chatDonationTitle,
    description: SettingsScreenString.chatDonationDescription,
    optionSet: settingsToggleOptionSet,
    read: (settings) => settings.showDonation,
    write: (settings, value) => settings.copyWith(showDonation: value),
    label: SettingsScreenString.toggleLabel,
    actionIcon: Icons.volunteer_activism_outlined,
  ),
  chatPreference(
    title: SettingsScreenString.chatUserBadgesTitle,
    description: SettingsScreenString.chatUserBadgesDescription,
    optionSet: settingsToggleOptionSet,
    read: (settings) => settings.showUserBadges,
    write: (settings, value) => settings.copyWith(showUserBadges: value),
    label: SettingsScreenString.toggleLabel,
    actionIcon: Icons.workspace_premium_outlined,
  ),
  chatPreference(
    title: SettingsScreenString.chatBadgeCollectorHeightTitle,
    description: SettingsScreenString.chatBadgeCollectorHeightDescription,
    optionSet: settingsBadgeCollectorPanelHeightOptionSet,
    read: (settings) => settings.badgeCollectorPanelHeight,
    write: (settings, value) => settings.copyWith(
      badgeCollectorPanelHeight: value,
    ),
    label: SettingsScreenString.percent,
    actionIcon: Icons.height,
  ),
  chatPreference(
    title: SettingsScreenString.chatBadgeCollectorPositionXTitle,
    description: SettingsScreenString.chatBadgeCollectorPositionXDescription,
    optionSet: settingsPositionOptionSet,
    read: (settings) => settings.overlayBadgeCollectorPositionX,
    write: (settings, value) => settings.copyWith(
      overlayBadgeCollectorPositionX: value,
    ),
    label: SettingsScreenString.percent,
    actionIcon: Icons.open_with,
  ),
  chatPreference(
    title: SettingsScreenString.chatBadgeCollectorPositionYTitle,
    description: SettingsScreenString.chatBadgeCollectorPositionYDescription,
    optionSet: settingsPositionOptionSet,
    read: (settings) => settings.overlayBadgeCollectorPositionY,
    write: (settings, value) => settings.copyWith(
      overlayBadgeCollectorPositionY: value,
    ),
    label: SettingsScreenString.percent,
    actionIcon: Icons.open_with,
  ),
  chatPreference(
    title: SettingsScreenString.chatBadgeCollectorDisplayTitle,
    description: SettingsScreenString.chatBadgeCollectorDisplayDescription,
    optionSet: settingsBadgeCollectorDisplayOptionSet,
    read: (settings) => settings.useBadgeCollector,
    write: (settings, value) => settings.copyWith(useBadgeCollector: value),
    label: SettingsScreenString.badgeCollectorLabel,
    actionIcon: Icons.collections_bookmark_outlined,
  ),
];
